### ISSUE TITLE
Saving the html pages

### ISSUE THREAD

**Issue by striker99** [coursera-dl/coursera-dl#438] opened 2016-01-30 19:44 UTC
First many thanks for the great tool that make our lives much easier!  

I wonder if it is possible to add an option (or make it default) to save all the html pages for a course. The reason I ask is because many of these pages contain course outline, reading lists, assignment instruction, data description, etc.

**Comment by balta2ar** [comment] 2016-01-31 08:14
Duplicate of #356.

**Closed by balta2ar** 2016-01-31 08:14 UTC
