### ISSUE TITLE
First time user: SystemError: parent module '' not loaded, cannot find relative import

### ISSUE THREAD

**Issue by jjmalave** [coursera-dl/coursera-dl#421] opened 2015-11-13 22:21 UTC
Hello devs,

So first, I installed Python 3.5 on my Windows 7 machine with python-3.5.0.exe. It updated the PATH var for all users.

I then installed cousera-dl by calling pip install --user coursera. Then I updated PATH with the courersa-dl.py directory path. C:\Users\<username>\appdata\roaming\python\python35\site-packages\coursera .

Still the cmd shell does not recognize coursera-dl.py or coursera-dl as a command. When I echo %PATH% it shows the coursera-dl path but still have to use the full path to call the script.

Secondly, I continue to get the following error:

C:\Users\<username>\Documents\My Projects\Coursera>C:\Users\<username>\AppData\Roaming\P
ython\Python35\site-packages\coursera\coursera_dl.py --debug -u ***** -p **** crypto
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Roaming\Python\Python35\site-packages\coursera\c
oursera_dl.py", line 72, in <module>
    from .cookies import (
SystemError: Parent module '' not loaded, cannot perform relative import

Any help would be great. My understanding is that "pip install --user coursera" would pull all requirements/dependencies and perform a full installation. But, if there is any extra dependency I need to resolve in addition to Python 3.5 then that would be good to know. 

Kind regards,
Javier

**Comment by ratijas** [comment] 2015-11-15 03:47
coursera-dl is very bad about supporting python3.
i've just `pip3 install` and tried to run it, and i've got:

`SyntaxError: Missing parentheses in call to 'print'`

python2.7 however is OK.

**Comment by jjmalave** [comment] 2015-11-22 05:23
Thanks Ratijas! It is working now. At least for non on-demand courses. Have no tried on-demand courses yet.

**Comment by balta2ar** [comment] 2016-01-28 15:03
Looks like the issue is solved. Closing.

**Closed by balta2ar** 2016-01-28 15:03 UTC
