### ISSUE TITLE
Some courses not at all sucessful:requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/<coursename>

### ISSUE THREAD

**Issue by sreebalineni** [coursera-dl/coursera-dl#450] opened 2016-02-23 15:19 UTC
For many sites, it starts getting some downloaded but after that we see the below errors
Downloading: python-network-data\01_getting-started\01_welcome\02_python-textbook_html_270.zip?response-content-type=application%2foctet-stream&a=1&response-content-disposition=attachment
Downloading https://d28rh4a8wq0iu5.cloudfront.net/pythonlearn/book/html_270.zip?response-content-type=application%2Foctet-stream&a=1&response-content-disposition=attachment -> python-network-data\01_getting-started\01_welcome\02_python-textbook_html_270.zip?response-content-type=application%2foctet-stream&a=1&response-content-disposition=attachment
Starting new HTTPS connection (1): d28rh4a8wq0iu5.cloudfront.net
Traceback (most recent call last):
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "C:\Users\Sreeman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/python-network-data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: python-network-data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\coursera_dl.py", line 1015, in download_on_demand_class
    args.resume
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\coursera_dl.py", line 528, in download_lectures
    downloader.download(url, lecfn, resume=resume)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "C:\Users\Sreeman\Downloads\coursera-dl-master\coursera-dl-master\coursera\downloaders.py", line 366, in _start_download
    f = open(filename, 'ab') if resume else open(filename, 'wb')
OSError: [Errno 22] Invalid argument: 'python-network-data\\01_getting-started\\01_welcome\\02_python-textbook_html_270.zip?response-content-type=application%2foctet-stream&a=1&response-content-disposition=attachment'

**Comment by balta2ar** [comment] 2016-02-23 15:52
@sreebalineni Try adding `--formats 'mp4 txt pdf doc'` to only download formats that you're interested in.

**Comment by jnowe** [comment] 2016-02-23 19:28
Same here, it's not possible to download contents from "power-electronics" course

**Comment by dareTake** [comment] 2016-02-24 12:16
I'm having the same problem, some of the content has been downloaded and the videos that the URL has problem with can be viewed in the browser.

Bug report,
Is the problem happening with the latest version of the script?
Yes

What operating system are you using?
Windows 10 x64

Do you have all the recommended versions of the modules? See them in the file requirements.txt.
Yes.


What is the course that you are trying to access?
hybrid-mobile-development

What is the precise command line that you are using (feel free to hide your username and password with asterisks, but leave all other information untouched).
coursera-dl -n --ignore-formats "txt" hybrid-mobile-development

What are the precise messages that you get? Please, use the --debug option before posting the messages as a bug report. Please, copy and paste them. Don't reword/paraphrase the messages
Please see attached bug report. 
[output.txt](https://github.com/coursera-dl/coursera-dl/files/144541/output.txt)

**Comment by xialu4820723** [comment] 2016-02-28 09:18
Is the problem happening with the latest version of the script?
Yes

What operating system are you using?
Windows 7 x64

Do you have all the recommended versions of the modules? See them in the file requirements.txt.
I used the commed "pip install coursera to" install it. Before I tried downloading the course, "pip install --upgrade coursera" commend was run.

What is the course that you are trying to access?
reproducible-research

What is the precise command line that you are using (feel free to hide your username and password with asterisks, but leave all other information untouched).
C:\Users\xia>coursera-dl -u ********** -p ********** reproducible-research --debug

What are the precise messages that you get? Please, use the --debug option before posting the messages as a bug report. Please, copy and paste them. Don't reword/paraphrase the messages.
root[main] Downloading class: reproducible-research
root[download_class] Downloading old style class reproducible-research
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file C:\Users\xia\AppData\Local\Temp\xia_
coursera_dl_cache\cookies\87384204@qq.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connectio
n (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /reproducible-resea
rch HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found for url: https://class.coursera.org/repr
oducible-research
root[download_class] Downloading new style (on demand) class reproducible-resear
ch
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=8RAoSTHCBJw2cWrrEJQ3; csrf2_token_X
MLPMhsz=BObiYt5ekOcubQni0e3hAKrL.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connectio
n (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP
/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
course/reproducible-research HTTP/1.1" 200 None
root[get_on_demand_syllabus] Downloaded https://www.coursera.org/api/opencourse.
v1/course/reproducible-research (15360 bytes)
root[parse_on_demand_syllabus] Parsing syllabus of on-demand course. This may ta
ke some time, be patient ...
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_CcsUnNYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_Ccs
UnNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_CcsUnNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_CcsUnNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_CcsUnNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_CcsUnNYEeW53xJZ7xvxhw>.
root[extract_links_from_supplement] Gathering supplement URLs for element_id <iE
P8r>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/onDemandSupple
ments.v1/-4ffSHNYEeWIfhKr_WcYsQ~iEP8r?includes=asset&fields=openCourseAssets.v1%
28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[extract_links_from_supplement] Gathering supplement URLs for element_id <i6
HnQ>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/onDemandSupple
ments.v1/-4ffSHNYEeWIfhKr_WcYsQ~i6HnQ?includes=asset&fields=openCourseAssets.v1%
28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[extract_links_from_supplement] Gathering supplement URLs for element_id <NZ
zA1>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/onDemandSupple
ments.v1/-4ffSHNYEeWIfhKr_WcYsQ~NZzA1?includes=asset&fields=openCourseAssets.v1%
28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_CiL5XNYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_CiL
5XNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_CiL5XNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_CiL5XNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_CiL5XNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_CiL5XNYEeW53xJZ7xvxhw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_BxWw3NYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_BxW
w3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_BxWw3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_BxWw3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_BxWw3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_BxWw3NYEeW53xJZ7xvxhw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAsse
ts.v1/B0qXDKQXEeWnogrP0sW75w HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <B0qXDKQXEeWnogrP0sW7
5w>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/assets.v1/AupK
uKQXEeWhURIQK_SaSw HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_B3dZ3NYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_B3d
Z3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_B3dZ3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_B3dZ3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_B3dZ3NYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_B3dZ3NYEeW53xJZ7xvxhw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_B4riHNYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_B4r
iHNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_B4riHNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_B4riHNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_B4riHNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_B4riHNYEeW53xJZ7xvxhw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_BzL9HNYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_BzL
9HNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_BzL9HNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_BzL9HNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_BzL9HNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_BzL9HNYEeW53xJZ7xvxhw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/
video/_B0aFXNYEeW53xJZ7xvxhw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <_B0a
FXNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_
id <_B0aFXNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of res
olution 540p of <_B0aFXNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for vid
eo_id <_B0aFXNYEeW53xJZ7xvxhw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for v
ideo_id <_B0aFXNYEeW53xJZ7xvxhw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAsse
ts.v1/P2Sgap3HEeW9ng5xPiEOCQ HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <P2Sgap3HEeW9ng5xPiEO
CQ>.
Traceback (most recent call last):
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://clas
s.coursera.org/reproducible-research

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: reproducible-research

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xia\AppData\Local\Programs\Python\Python35-32\Scripts\coursera-
dl-script.py", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "c:\users\xia\appdata\local\programs\python\python35-32\lib\site-packages
\coursera\api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by dareTake** [comment] 2016-03-12 15:47
Hm, I wonder if anyone is looking into the issue ? 
I'm having trouble with like 3 courses, and they're ending soon.

**Comment by balta2ar** [comment] 2016-03-12 16:11
There is an unmerged pull request #451 that may help you. Try it.

**Comment by dareTake** [comment] 2016-03-13 04:32
@balta2ar Thank you, the pull request solves my issue.

**Comment by balta2ar** [comment] 2016-03-15 14:55
The pull request has been merged into master. Closing.

**Closed by balta2ar** 2016-03-15 14:55 UTC

**Comment by marcosorapis** [comment] 2016-06-23 14:45
Hello, with the coursera-dl -u xxx -p yyy compensation-management I'm having the KeyError: 'assetId'. I'm not familiar in how to do the pull request. May you give me a piece of advice?
Thank you!

**Comment by balta2ar** [comment] 2016-06-23 15:19
The problem was fixed a long ago. Make sure to use the latest version of `coursera-dl` pip package: `sudo pip install --upgrade coursera-dl`
