### ISSUE TITLE
HTTPError 404 Client Error

### ISSUE THREAD

**Issue by ruilinch** [coursera-dl/coursera-dl#588] opened 2017-02-17 03:05 UTC
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Have trouble finding courses.  Get HTTPError 404 Client Error.  

For example, for the course [the Modern and the Post-Modern](https://www.coursera.org/learn/modern-postmodern-1/home/welcome), based on the website address of this course, I assume that the CLASS_NAME of this course is "modern-postmodern-1".  
But when I run  
`coursera-dl -n"coursera.netrc" classnames"modern-postmodern-1"
`  
I ended up having errors:  
`coursera_dl version 0.8.0
Downloading class: classnamesmodern-postmodern-1 (1 / 1)
Logged in on coursera.org.
Error 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/classnamesmodern-postmodern-1?showLockedItems=true getting page https://www.coursera.org/api/opencourse.v1/course/classnamesmodern-postmodern-1?showLockedItems=true
The server replied: {"errorCode":null,"message":"Course not found: CourseSlug(Slug(classnamesmodern-postmodern-1))","details":null}
HTTPError 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/classnamesmodern-postmodern-1?showLockedItems=true`
  
Is this because I have entered the wrong CLASS_NAME?

### Your environment
* Operating System (name/version): macOS 10.12
* Python version: 2.7
* coursera-dl version: 0.8.0

**Comment by balta2ar** [comment] 2017-02-17 05:33
@ruilinch Yes, class name should be just "modern-postmodern-1", e.g.:
```
coursera-dl -n coursera.netrc modern-postmodern-1
```

**Comment by balta2ar** [comment] 2017-08-26 18:56
Closing. Feel free to comment if the issue is still there.

**Closed by balta2ar** 2017-08-26 18:56 UTC
