### ISSUE TITLE
Does coursera-dl supports download quiz contents, final exams and exercises?

### ISSUE THREAD

**Issue by madushan1000** [coursera-dl/coursera-dl#364] opened 2015-05-25 08:13 UTC
Some courses have interactive exercises in the middle of the video, course notes, quizzes and past exam papers. Is the functionality for downloading these already implemented?

**Comment by mxamin** [comment] 2015-05-25 08:25
Can you give us some examples?

**Comment by madushan1000** [comment] 2015-05-25 09:10
For example this lecture video (https://class.coursera.org/intrologic-004/lecture/3 ) has an interactive exercise at 3:14. 
And this course (https://class.coursera.org/logic2-002) has course notes section and a homework quiz section.

**Comment by balta2ar** [comment] 2015-08-07 13:42
Not sure about in-video quizzes, regular quizzes and exams, but related materials and assignment pages are very valuable. Sometimes they contain description and steps for implementations. I definitely want this feature at least partially be implemented.

**Comment by balta2ar** [comment] 2015-08-07 13:44
Possible duplicate of #356. Or at least related to.

**Comment by rbrito** [comment] 2015-08-15 00:33
Thanks @balta2ar and others.

Yes, this issue is a duplicate of #356. I'm closing this then. Let's move the discussion there.

Thanks for all the feedback,

Rogério.

**Closed by rbrito** 2015-08-15 00:33 UTC
Labels: duplicate, enhancement, help-needed
