### ISSUE TITLE
SSLError HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/login/v3

### ISSUE THREAD

**Issue by fredharvey** [coursera-dl/coursera-dl#661] opened 2018-06-02 15:40 UTC
Before you flame me, This started happening mid-day after many successful downloads without environment changes. 

AGAIN - before you flame. this was working and suddenly stopped after about 14 downloads. I have a simple .bat file that automates some of the downloads and scripts that worked at 10a no longer worked at 2p without coding or environment changes. Why did scripts work and then not? 

===>>Can anyone verify that they can download? 

I've also tried to setup a new machine with a different IP address to rule out profile or IP blockage. 

### Subject of the issue
Setup coursera-dl and successfully started downloading courses I have access to for archival and mobile purposes (I like to work disconnected on my laptop with the reading materials and videos, etc). 

coursera-dl stopped working and started reporting:
SSLError HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))

### Your environment
* Operating System (name/version): Microsoft Windows [Version 10.0.17134.48]
* Python version: Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
* coursera-dl version: coursera_dl version 0.10.0

### Steps to reproduce
1. download and install 64bit Python on Windows (add to path, remove path size limt)
2. open command prompt & type " pip install coursera-dl"
3. type "coursera-dl -u {yourUserName, yes, i put my real one here} {coursename, yes, i put a real one here}

* Is the problem happening with the latest version of the script? YES
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. YES
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Should download the course

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

*** /START Direct Output from Script Below ***
coursera_dl version 0.10.0
Downloading class: duke-behavioral-finance (1 / 1)
SSLError HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))

#####################################################################
# ATTENTION! PLEASE READ THIS!
#
# The following error has just occurred:
# SSLError HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))
#
# Please read instructions on how to fix this error here:
# https://github.com/coursera-dl/coursera-dl#sslerror-errno-1-_sslc504-error14094410ssl-routinesssl3_read_bytessslv3-alert-handshake-failure
#####################################################################
*** /END Direct Output from Script Below ***

**Comment by balta2ar** [comment] 2018-06-02 15:51
Try this pull request: https://github.com/coursera-dl/coursera-dl/pull/660

**Comment by balta2ar** [comment] 2018-06-02 16:06
Just merged into master, you can also try there, but it's working for me.

**Comment by balta2ar** [comment] 2018-06-02 17:29
Pushed version 0.11.0 to PyPI.

**Comment by fredharvey** [comment] 2018-06-02 19:38
tried upgrading and then uninstalling/reinstalling PyPl and get this

c:\>pip install coursera-dl
Collecting coursera-dl
  Using cached https://files.pythonhosted.org/packages/5d/a9/375faccc6458723f6baa867b2dd6d9cd9d0caf49786d74d8c3a267f703b0/coursera-dl-0.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\fred\AppData\Local\Temp\pip-install-25u030p8\coursera-dl\setup.py", line 62, in <module>
        'Generate README.rst from README.md via pandoc!\n\nExample: '
      File "C:\Users\fred\AppData\Local\Temp\pip-install-25u030p8\coursera-dl\setup.py", line 52, in read_file
        lines = f.read()
      File "c:\users\fred\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2587: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\fred\AppData\Local\Temp\pip-install-25u030p8\coursera-dl\

**Comment by TheGoddessInari** [comment] 2018-06-02 20:11
I saw this too, #662 should fix it.

**Comment by balta2ar** [comment] 2018-06-02 20:21
Pushed version 0.11.1 to PyPI.

**Comment by fredharvey** [comment] 2018-06-02 21:53
thank you all :)

**Comment by balta2ar** [comment] 2018-06-03 08:32
Pushed version 0.11.2 to PyPI.

**Closed** 2018-06-03 08:31 UTC

**Comment by AmateurAtThis** [comment] 2018-06-09 19:02
Hi,

i'm getting this here too:

SSLError HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))

i tried:
- upgrading coursera-dl (was already the latest verion)
- pip install --user urllib3 pyasn1 ndg-httpsclient pyOpenSSL (already statisfied)
-#660

any other tips? Sorry, I'm new to this whole coding thing and i have no clue on how to fix this.

**Comment by balta2ar** [comment] 2018-06-09 19:10
Could you verify that you're indeed running 0.11.2?
```
$ coursera-dl --version
0.11.2
```
What's your version of Python?
Could you try this? https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

**Comment by AmateurAtThis** [comment] 2018-06-09 19:19
oh, you're right! I just ran 

`coursera-dl --version` in PowerShell and apparantley it's 0.10.

python version is 3.6 but i usually downlod courses via PowerShell with

`coursera-dl -u "username" -p "password" --path C:\Users\MyName\Videos\Courses\Coursera investing-in-stocks`

when i put in `pip install --upgrade coursera-dl` into the PowerShell i get this.

`Requirement already up-to-date: coursera-dl in c:\users\tobias\appdata\roaming\python\python36\site-packages (0.11.2)
Requirement not upgraded as not directly required: beautifulsoup4>=4.1.3 in c:\program files\python36\lib\site-packages (from coursera-dl) (4.6.0)
Requirement not upgraded as not directly required: requests>=2.10.0 in c:\program files\python36\lib\site-packages (from coursera-dl) (2.18.4)
Requirement not upgraded as not directly required: six>=1.5.0 in c:\program files\python36\lib\site-packages (from coursera-dl) (1.11.0)
Requirement not upgraded as not directly required: urllib3>=1.10 in c:\program files\python36\lib\site-packages (from coursera-dl) (1.22)
Requirement not upgraded as not directly required: pyasn1>=0.1.7 in c:\program files\python36\lib\site-packages (from coursera-dl) (0.4.3)
Requirement not upgraded as not directly required: keyring>=4.0 in c:\program files\python36\lib\site-packages (from coursera-dl) (12.2.1)
Requirement not upgraded as not directly required: configargparse>=0.12.0 in c:\program files\python36\lib\site-packages (from coursera-dl) (0.13.0)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in c:\program files\python36\lib\site-packages (from requests>=2.10.0->coursera-dl) (3.0.4)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in c:\program files\python36\lib\site-packages (from requests>=2.10.0->coursera-dl) (2018.4.16)
Requirement not upgraded as not directly required: idna<2.7,>=2.5 in c:\program files\python36\lib\site-packages (from requests>=2.10.0->coursera-dl) (2.6)
Requirement not upgraded as not directly required: entrypoints in c:\program files\python36\lib\site-packages (from keyring>=4.0->coursera-dl) (0.2.3)
Requirement not upgraded as not directly required: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\program files\python36\lib\site-packages (from keyring>=4.0->coursera-dl) (0.1.2)`

**Comment by balta2ar** [comment] 2018-06-09 19:36
So has it upgraded after pip upgrade? Or not?

**Comment by AmateurAtThis** [comment] 2018-06-09 19:47
still showing 0.10

**Comment by TheGoddessInari** [comment] 2018-06-09 19:50
Just uninstall and reinstall coursera-dl. It sounds like the metadata got out of date with the actual installed version.

**Comment by AmateurAtThis** [comment] 2018-06-09 20:03
okay, i will try that

**Comment by AmateurAtThis** [comment] 2018-06-09 20:15
Somehow I can not uninstall it...

> Uninstalling coursera-dl-0.10.0:
  Would remove:
    c:\program files\python36\lib\site-packages\coursera\*
    c:\program files\python36\lib\site-packages\coursera_dl-0.10.0-py3.6.egg-info
    c:\program files\python36\scripts\coursera-dl-script.py
    c:\program files\python36\scripts\coursera-dl.exe
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] Zugriff verweigert: 'c:\\program files\\python36\\lib\\site-packages\\coursera\\__init__.py' -> 'C:\\Users\\Tobias\\AppData\\Local\\Temp\\pip-uninstall-yc7xascv\\program files\\python36\\lib\\site-packages\\coursera\\__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\_internal\commands\uninstall.py", line 68, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "c:\program files\python36\lib\site-packages\pip\_internal\req\req_install.py", line 661, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "c:\program files\python36\lib\site-packages\pip\_internal\req\req_uninstall.py", line 219, in remove
    renames(path, new_path)
  File "c:\program files\python36\lib\site-packages\pip\_internal\utils\misc.py", line 273, in renames
    shutil.move(old, new)
  File "c:\program files\python36\lib\shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [WinError 5] Zugriff verweigert: 'c:\\program files\\python36\\lib\\site-packages\\coursera\\__init__.p 

>

**Comment by balta2ar** [comment] 2018-06-09 20:28
Try uninstalling in a Shell started as an Administrator.

**Comment by AmateurAtThis** [comment] 2018-06-09 20:55
okay, that worked...re-installing too, but one line concerns me

`requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.`

later in the code it says `Successfully installed coursera-dl-0.11.2`

So, I'll just give it a go now

**Comment by AmateurAtThis** [comment] 2018-06-09 20:56
okay...so trying to download a course gives me this:

> Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.23 (c:\program files\python37\lib\site-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\coursera-dl-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.23 (c:\program files\python37\lib\site-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), {'requests'})

>

**Comment by balta2ar** [comment] 2018-06-09 21:10
I guess you can force remove urllib3 1.23 (again, using Admin shell) and reinstall coursera-dl to that it installs urllib3 of a lower, but compatible version, but be wary that it may break other packages that depend on urllib3, that you may be using.

**Comment by AmateurAtThis** [comment] 2018-06-10 09:19
So, I uninstalled coursera-dl and python. I deleted everything, every shred of data.

I reinstalled python to C:\Python instead of C:\Program Files\Python and i set up coursera-dl again and now everything works perfectly.

I guess at some point I made a mistake and that triggered the handshake. Anyways...I just wanted to say thank you for your support and that I appreciate it :)

**Comment by kishoreo** [comment] 2018-09-05 10:41
Please Help me , I could not able to download the courses
C:\Users\Kishore Odugu>coursera-dl -u myusername -p mypassword ml-regression
coursera_dl version 0.11.4
Traceback (most recent call last):
File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
chunked=chunked)
File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
self._validate_conn(conn)
File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 849, in validate_conn
conn.connect()
File "c:\python37\lib\site-packages\urllib3\connection.py", line 356, in connect
ssl_context=context)
File "c:\python37\lib\site-packages\urllib3\util\ssl.py", line 359, in ssl_wrap_socket
return context.wrap_socket(sock, server_hostname=server_hostname)
File "c:\python37\lib\ssl.py", line 412, in wrap_socket
session=session
File "c:\python37\lib\ssl.py", line 850, in _create
self.do_handshake()
File "c:\python37\lib\ssl.py", line 1108, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\python37\lib\site-packages\requests\adapters.py", line 445, in send
timeout=timeout
File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "c:\python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Python37\Scripts\coursera-dl.exe_main.py", line 9, in 
File "c:\python37\lib\site-packages\coursera\coursera_dl.py", line 236, in main
login(session, args.username, args.password)
File "c:\python37\lib\site-packages\coursera\cookies.py", line 146, in login
headers=headers, allow_redirects=False)
File "c:\python37\lib\site-packages\requests\sessions.py", line 559, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "c:\python37\lib\site-packages\requests\sessions.py", line 512, in request
resp = self.send(prep, **send_kwargs)
File "c:\python37\lib\site-packages\requests\sessions.py", line 622, in send
r = adapter.send(request, **kwargs)
File "c:\python37\lib\site-packages\requests\adapters.py", line 511, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))

C:\Users\Kishore Odugu>
