### ISSUE TITLE
The website of coursera has a revision, CLASS_NAME could not be found as url changes

### ISSUE THREAD

**Issue by xialu4820723** [coursera-dl/coursera-dl#432] opened 2016-01-07 01:46 UTC
I'm learning on coursera and your program helps me a lot, thank you.

Coursera has a revision on January 5. The url has changed a lot.For example, the home page of class "R" has been changed to:
https://www.coursera.org/learn/r-programming/home/welcome
There is no sign of it's CLASS_NAME of old version(rprog-035) , I have tried downloading "r-programming", but coursera-dl told me "Could not find class : r-programming".

So for now I don't know where to find the right course name used at coursera-dl. So... that's my problem, thank you.

**Comment by himabinduboda** [comment] 2016-01-07 04:18
If its a OnDemand course, you need to use --on-demand option

**Comment by jspraul** [comment] 2016-01-13 03:03
#420 - need to use the latest version

**Comment by xialu4820723** [comment] 2016-01-14 11:59
I tried to download "data cleaning" course yesterday, after adding the --on-demand option the download started successfully. Thank you for your help.

**Comment by balta2ar** [comment] 2016-01-28 14:56
Looks like the issue is solved. Closing.

**Closed by balta2ar** 2016-01-28 14:56 UTC
