### ISSUE TITLE
Please Help coursera dl login Error (HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3)

### ISSUE THREAD

**Issue by afandy89** [coursera-dl/coursera-dl#707] opened 2019-02-23 11:15 UTC
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "P:\GitHub dl\DL\Coursera\2\coursera-dl-master\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:\GitHub dl\DL\Coursera\2\coursera-dl-master\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "P:\GitHub dl\DL\Coursera\2\coursera-dl-master\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "P:\GitHub dl\DL\Coursera\2\coursera-dl-master\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by balta2ar** [comment] 2019-02-23 13:53
Duplicate of https://github.com/coursera-dl/coursera-dl/issues/702.

**Closed by balta2ar** 2019-02-23 13:53 UTC
