### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by dheereshaggarwal** [coursera-dl/coursera-dl#710] opened 2019-03-05 20:25 UTC
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
can't download anything

### Your environment
* Operating System (name/version): Ubuntu 18.04
* Python version: latest version
* coursera-dl version: latest version

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
It should download the videos

### Actual behaviour
##I have used coursera-dl before but this time this error is happening. My login credentials are correct.
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/usr/local/lib/python3.6/dist-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by balta2ar** [comment] 2019-03-06 05:12
Duplicate of https://github.com/coursera-dl/coursera-dl/issues/702.

**Closed by balta2ar** 2019-03-06 05:12 UTC
