### ISSUE TITLE
Bad Request for url: https://api.coursera.org/api/login/v3

### ISSUE THREAD

**Issue by vikiaiteam** [coursera-dl/coursera-dl#704] opened 2019-02-06 20:11 UTC
oursera_dl version 0.11.4
isting enrolled courses
raceback (most recent call last):
 File "c:\python37-32\lib\site-packages\coursera\cookies.py", line 148, in login
   r.raise_for_status()
 File "c:\python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
equests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

uring handling of the above exception, another exception occurred:

raceback (most recent call last):
 File "c:\python37-32\lib\runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "c:\python37-32\lib\runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "C:\Python37-32\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
 File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 232, in main
   list_courses(args)
 File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 108, in list_courses
   login(session, args.username, args.password)
 File "c:\python37-32\lib\site-packages\coursera\cookies.py", line 155, in login
   raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
oursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by balta2ar** [comment] 2019-02-07 11:37
Duplicate of https://github.com/coursera-dl/coursera-dl/issues/702.

**Closed by balta2ar** 2019-02-07 11:37 UTC
