### ISSUE TITLE
inconsistency in courses downloading/on-demand issues

### ISSUE THREAD

**Issue by illuzioner** [coursera-dl/coursera-dl#419] opened 2015-11-09 17:15 UTC
There are several courses I've tried to download that fail.  I switched to including the cookies option (-c) and that helped for 2 courses, but several others remain.

The documentation states to use the option "--on-demand" for on demand courses.  When you use that option, it states that "--on-demand" has been deprecated.  There are two on-demand courses that the url looks incorrect when coursera-dl tries to access them.  

For the courser intro to public speaking, the URL is:
https://www.coursera.org/learn/public-speaking/home/welcome

And this is what coursera-dl tries to access:
https://class.coursera.org/public-speaking/lecture

It's trying to access an on-demand course with a not on-demand URL and gives a 404 error.  But there is no way to tell it that it's an on-demand course.

I have the same issue with the course what-is-social:
https://www.coursera.org/learn/what-is-social/home/welcome

**Comment by balta2ar** [comment] 2015-11-09 18:24
When submitting an issue, please provide as much information to reproduce the problem as you can. Developers can't read your mind.

What exactly is your command line?
What is the output of coursera-dl?
What version are you using? (that is obvious in your case but if it weren't about on-demand, it would be very important to state it)

I've just enrolled to on-demand version on public-speaking, ran the command as follows and it downloaded the course just fine:
``` bash
coursera-dl --aria2 -n --path . public-speaking
```

I used this command to download the old version (I think I was already enrolled to some older run of the course):
``` bash
coursera-dl --aria2 -n --path . publicspeak-002
```

Looks like old-styled courses have numbers in their names.

**Comment by balta2ar** [comment] 2016-01-28 15:36
Looks like the issue is abandoned. If you're still experiencing the problem, please try using the latest github version.  If you have any troubles, feel free to report here. I'm closing the issue for now.

**Closed by balta2ar** 2016-01-28 15:36 UTC
