### ISSUE TITLE
404

### ISSUE THREAD

**Issue by iqinqin** [coursera-dl/coursera-dl#655] opened 2018-05-08 11:16 UTC
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
E:\>coursera-dl dsp -c cookies.txt --path E:\ --debug
root[main] Downloading class: dsp
root[download_class] Downloading old style class dsp
root[load_cookies_file] Loading cookie file cookies.txt into memory.
root[get_cookies_for_class] Loaded cookies from cookies.txt
root[download_about] About file to be written to: E:\dsp-about.json
root[download_about] About url: https://api.coursera.org/api/catalog.v1/courses?
fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHover,uni
versityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,faq,cou
rseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkload,abo
utTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=dsp
root[download_about] Downloading about page from: https://api.coursera.org/api/c
atalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,
smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targ
etAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimate
dClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=s
earch&query=dsp
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.courser
a.org
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "GET /api/cat
alog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,sm
allIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,target
Audience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedC
lassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=sea
rch&query=dsp HTTP/1.1" 404 None
root[get_page] Error 404 Client Error: Not Found for url: https://api.coursera.o
rg/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,sm
allIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCou
rse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,
estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguage
sCsv&q=search&query=dsp getting page https://api.coursera.org/api/catalog.v1/cou
rses?fields=largeIcon,photo,previewLink,shortDescription,smallIcon,smallIconHove
r,universityLogo,universityLogoSt,video,videoId,aboutTheCourse,targetAudience,fa
q,courseSyllabus,courseFormat,suggestedReadings,instructor,estimatedClassWorkloa
d,aboutTheInstructor,recommendedBackground,subtitleLanguagesCsv&q=search&query=d
sp
root[main] HTTPError 404 Client Error: Not Found for url: https://api.coursera.o
rg/api/catalog.v1/courses?fields=largeIcon,photo,previewLink,shortDescription,sm
allIcon,smallIconHover,universityLogo,universityLogoSt,video,videoId,aboutTheCou
rse,targetAudience,faq,courseSyllabus,courseFormat,suggestedReadings,instructor,
estimatedClassWorkload,aboutTheInstructor,recommendedBackground,subtitleLanguage
sCsv&q=search&query=dsp

### Your environment
* Operating System (name/version):Windows 7
* Python version:python 3.6.5
* coursera-dl version:0.10.0

**Comment by balta2ar** [comment] 2018-05-08 12:35
Duplicate of #634.

**Comment by iqinqin** [comment] 2018-05-09 02:00
@balta2ar The problem is same, but has not solved.

**Closed** 2018-06-24 07:59 UTC
