### ISSUE TITLE
assitid error

### ISSUE THREAD

**Issue by AhmedA-del** [coursera-dl/coursera-dl#455] opened 2016-03-15 11:21 UTC
when i trying to download 
https://www.coursera.org/learn/learning-how-to-learn 
it says 
Downloading class: learning-how-to-learn
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/learning-how-to-
learn
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/learning-how-to-lea
rn (38534 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering video URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
Proceeding with download of resolution 540p of <mGhggl_JEeSfFCIACxcQxA>.
Gathering subtitle URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
Gathering transcript URLs for video_id <mGhggl_JEeSfFCIACxcQxA>.
Traceback (most recent call last):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://clas
s.coursera.org/learning-how-to-learn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: learning-how-to-learn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python35-32\Scripts\courser
a-dl-script.py", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "c:\users\ahmed\appdata\local\programs\python\python35-32\lib\site-packag
es\coursera\api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by balta2ar** [comment] 2016-03-15 12:00
Duplicate of #442. I've just merged #451, please do `git pull` and try again.

**Closed by balta2ar** 2016-03-15 12:00 UTC
