### ISSUE TITLE
Bad Request for url: https://api.coursera.org/api/login/v3

### ISSUE THREAD

**Issue by StevinWilson** [coursera-dl/coursera-dl#726] opened 2019-05-22 05:41 UTC
### Subject of the issue
Error while trying to download course materials.

### Your environment
* Operating System (name/version): Manjaro Linux 18.0.4 
* Python version: 3.7
* coursera-dl version:  0.11.4 (Installed using pip)

### Steps to reproduce
coursera-dl -u username machine-learning
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Coursera password for username: 
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/usr/lib/python3.7/site-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/usr/lib/python3.7/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by matheusportela** [comment] 2019-05-22 14:29
Did you try using the script without the `-p` parameter? I was having this problem and solved by passing the password afterward. I suspect the special characters in my password caused this error.

**Comment by StevinWilson** [comment] 2019-05-22 14:36
Yes, I tried the command without the password parameter. Got the same error. Thank you

On May 22, 2019 10:29 AM, Matheus Vieira Portela <notifications@github.com> wrote:

Did you try using the script without the -p parameter? I was having this problem and solved by passing the password afterward. I suspect the special characters in my password caused this error.

**Comment by matheusportela** [comment] 2019-05-22 16:11
What really worked for me was this approach: https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-488006595. You should try it.

**Comment by MJZzzz** [comment] 2019-06-23 23:30
You may need root privilege, run sudo su.

**Comment by StevinWilson** [comment] 2019-06-24 00:28
Thank you. I will try that.

On Jun 23, 2019 7:30 PM, MJZzzz <notifications@github.com> wrote:

You may need root privilege, run sudo su.

**Comment by Jadiker** [comment] 2019-06-27 20:57
[This trick](https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-459827717) worked the best for me. Close all tabs related to Coursera (recommended [here](https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-459736264)). Sign into the [Coursera Help Center](https://learner.coursera.help/hc/en-us), leave just that tab up, and then try running the script with just the normal `-u` with your username and `-p` with the password. It took me about 5 tries running it in a row for it to suddenly work.

(I also did copy/paste this `[coursera-dl.py](https://github.com/jethar/coursera-dl/blob/fix_bad_request_api_v3/coursera/coursera_dl.py)` file as my `coursera-dl.py` file as recommended [here](https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-492504978), but I don't think this had any impact on my success, since the cookie solution did not work for me at all.)

**Comment by StevinWilson** [comment] 2019-07-21 10:39
@Jadiker - Thank you so much. I tried the same method and it worked the third time I ran the same command.

**Comment by raffam** [comment] 2019-07-21 22:39
@Jadiker yeah that did it. Its is funny though, what is this bug due to?

**Comment by Jadiker** [comment] 2019-07-22 17:50
> @Jadiker yeah that did it. Its is funny though, what is this bug due to?

Sadly, the best explanation I've seen is that it's a Coursera server issue: https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-460532152 and https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-459714832

I personally do not know enough to be able to say what the problem is.

**Comment by Jadiker** [comment] 2019-07-22 17:52
Duplicate of #702

**Comment by raffam** [comment] 2019-08-11 06:01
> Close all tabs related to Coursera (recommended here). Sign into the Coursera Help Center, leave just that tab up, and then try running the script with just the normal -u with your username and -p with the password. It took me about 5 tries running it in a row for it to suddenly work.

Apparently only the last phrase seems relevant to me.

I have tried leaving the coursera tab open in Google Chrome to whatever page there is, and inserting the coursera-dl command in a loop inside a batch file. After the first tried where it fails to connects, suddenly at the 5th/6th try coursera-dl is suddenly able to login again and the course is correctly downloaded

**Comment by rosseyman** [comment] 2019-08-22 21:33
What worked for me, delete all cookies for coursera, then close all coursera tabs then follow Jadiker's trick. using the help site: https://learner.coursera.help/hc/en-us

**Comment by aurora-of-earth** [comment] 2019-09-14 19:16
> You may need root privilege, run sudo su.

Worked like a charm, thanks.

**Comment by balta2ar** [comment] 2019-12-16 20:53
duplicate of #702, closing

**Closed by balta2ar** 2019-12-16 20:53 UTC

**Comment by haiyunsky** [comment] 2020-01-15 00:47
https://www.coursera.org/, login error  Bad Request , What happened?

**Comment by JongukPark** [comment] 2020-01-15 01:41
> https://www.coursera.org/, login error Bad Request , What happened?

me too..
something is wrong in login system

**Comment by haiyunsky** [comment] 2020-01-15 05:03
How did you solve this problem?

> > https://www.coursera.org/, login error Bad Request , What happened?
> 
> me too..
> something is wrong in login system

**Comment by imthefrizzlefry** [comment] 2020-03-29 18:30
I still observe this issue every time I use the tool.  I have been unable to use it for months.

**Comment by AbhimanyuAryan** [comment] 2020-07-06 23:48
answer here: https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-488006595
<img width="833" alt="Screenshot 2020-07-07 at 5 18 28 AM" src="https://user-images.githubusercontent.com/8083613/86669557-561dec00-c011-11ea-8974-b9e5633d3bf8.png">

**Comment by mararkeri** [comment] 2020-09-16 12:25
Create a file coursera-dl.conf in the same directory of the coursera-dl with the text below:
--username <email_here>
--password <passwd_here>
--subtitle-language en
--cauth

cauth value will be available only if you login to coursera and then check in cookies.
You may check the following video:
https://youtu.be/xpy0H4T9zHU
