### ISSUE TITLE
SSL3_READ_BYTES:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by SiriusFuenmayor** [coursera-dl/coursera-dl#373] opened 2015-07-02 19:15 UTC
Hi, when i run the command:

./coursera-dl -u my_user_name -p my_password compneuro-003

I get the following error:

requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

I'm using the last version of coursera-dl to date.

**Comment by SiriusFuenmayor** [comment] 2015-07-02 20:57
I'm using ubuntu 14.04

**Comment by rbrito** [comment] 2015-08-14 23:56
Hi.

Could you please post your results of the document at https://github.com/coursera-dl/coursera-dl/issues/377#issuecomment-131268395 to issue #377?  I would *really* appreciate any extra information that you can provide, since that would make it easier to find what varies and what doesn't with the various systems that exhibit the problem.

In fact, even if people have worked around the problem with Python 3, but can still reproduce the problem with Python 2 would be welcome to post the difference in their setups.

I'm closing this bug report as it seems a duplicate of that problem.

Again, please post extra information to issue #377.

Thank you very much,

Rogério.

**Closed by rbrito** 2015-08-14 23:56 UTC
Labels: bug, duplicate
