### ISSUE TITLE
403 on one pdf file in orgchem1a-001

### ISSUE THREAD

**Issue by raszpl** [coursera-dl/coursera-dl#153] opened 2013-07-04 17:51 UTC
H:_learning>c:\Python27\python.exe _coursera/coursera_dl.py --verbose-dirs --aria2 -u X -p Y orgchem1a-001

...
Downloading: orgchem1a-001\ORGCHEM1A-001_03_Week_3\04_3.4_Common_Mistakes_Made_in_Drawing_Resonance_Contributors.pdf

07/04 19:46:31 [ERROR] CUID#6 - Download aborted. URI=https://d396qusza40orc.cloudfront.net/orgchem1a/%20lecture_slides%2FWeek3%2F3.4%20Common%20Mistakes%20Made%20in%20Drawing%20Re
sonance%20Contributors.pdf
Exception: [AbstractCommand.cc:314] errorCode=22 URI=https://d396qusza40orc.cloudfront.net/orgchem1a/%20lecture_slides%2FWeek3%2F3.4%20Common%20Mistakes%20Made%20in%20Drawing%20Res
onance%20Contributors.pdf
  -> [HttpSkipResponseCommand.cc:224] errorCode=22 The response status is not successful. status=403

07/04 19:46:31 [NOTICE] Download GID#735f8b82c219f7f4 not complete: H:/_learning/orgchem1a-001/ORGCHEM1A-001_03_Week_3/04_3.4_Common_Mistakes_Made_in_Drawing_Resonance_Contributors
.pdf

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
735f8b|ERR |       0B/s|H:/_learning/orgchem1a-001/ORGCHEM1A-001_03_Week_3/04_3.4_Common_Mistakes_Made_in_Drawing_Resonance_Contributors.pdf

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
...

it tries to download from:

https://d396qusza40orc.cloudfront.net/orgchem1a/%20lecture_slides%2FWeek3%2F3.4%20Common%20Mistakes%20Made%20in%20Drawing%20Resonance%20Contributors.pdf

but going directly to the course webpage and clicking on pdf icon you get this link instead:

https://spark-public.s3.amazonaws.com/orgchem1a/lecture_slides/Week3/3.4%20Common%20Mistakes%20Made%20in%20Drawing%20Resonance%20Contributors.pdf

I tested few other random files from this course and they download fine

**Comment by balta2ar** [comment] 2018-06-11 15:52
The issue is about the old platform which is several years retired. Closing as outdated.

**Closed by balta2ar** 2018-06-11 15:52 UTC
Labels: bug, enhancement
