### ISSUE TITLE
Bad request error on latest docker image

### ISSUE THREAD

**Issue by moein7tl** [coursera-dl/coursera-dl#703] opened 2019-02-04 08:24 UTC
Using docker to download course will fail because of bad request to coursera.

`docker run --rm -it -v   "$(pwd):/courses"     courseradl/courseradl -u $MY_USER -p $MY_PASSWORD machine-learning
`
 produced error:

```
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/usr/local/lib/python3.6/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

```

**Comment by balta2ar** [comment] 2019-02-04 11:04
Duplicate of https://github.com/coursera-dl/coursera-dl/issues/702.

**Closed by balta2ar** 2019-02-04 11:04 UTC
