### ISSUE TITLE
unable to download courses 

### ISSUE THREAD

**Issue by nithinsihu** [coursera-dl/coursera-dl#708] opened 2019-02-25 08:02 UTC
hi , i am new to coursera.dl, i done all the installation steps.
when i try list command, it produce this error..

c:\test\coursera-dl-master>coursera-dl  --list-courses -u *** --debug
Coursera password for ***:
root[main] coursera_dl version 0.11.4
root[main] Listing enrolled courses
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=FINXrzGjX95yCv3X0nYn; csrf2_token_0ucxPIVi=t4obo9gfQAhXaaFqUUAA0z3N.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 None
Traceback (most recent call last):
  File "c:\test\coursera-dl-master\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\..\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\test\coursera-dl-master\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "c:\test\coursera-dl-master\coursera\coursera_dl.py", line 232, in main
    list_courses(args)
  File "c:\test\coursera-dl-master\coursera\coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "c:\test\coursera-dl-master\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

how can i rectifi this error .

**Comment by balta2ar** [comment] 2019-02-25 10:54
Duplicate of https://github.com/coursera-dl/coursera-dl/issues/702.

**Closed by balta2ar** 2019-02-25 10:54 UTC
