### ISSUE TITLE
excuse me, I can't use aria2 for downloading

### ISSUE THREAD

**Issue by KwToPA** [coursera-dl/coursera-dl#479] opened 2016-04-22 00:52 UTC
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I can't use external downloader aria2

### Your environment
* Operating System (name/version): OS x 10.10.5
* Python version: 2.7.6
* coursera-dl version: last

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?   Y 
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.  N 
* What is the course that you are trying to access?  neuralnets-2012-001
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
```
proxychains4 coursera-dl --aria2 -u <user> -p <passward> -f "pptx srt mp4" neuralnets-2012-001
```
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
```
proxychains4 coursera-dl --aria2 -u <user> -p <passward> -f "pptx srt mp4" neuralnets-2012-001
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.7/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.7/lib/libproxychains4.dylib
[proxychains] DLL init
[proxychains] DLL init
Downloading class: neuralnets-2012-001
Starting new HTTPS connection (1): class.coursera.org
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  class.coursera.org:443  ...  OK
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Starting new HTTPS connection (1): www.coursera.org
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.coursera.org:443  ...  OK
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

### Expected behaviour
aria2 works

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by balta2ar** [comment] 2016-06-12 12:38
Duplicate of #480.

**Closed by balta2ar** 2016-06-12 12:38 UTC
