### ISSUE TITLE
Cannot download - "Connection pool is full"

### ISSUE THREAD

**Issue by lordloh** [coursera-dl/coursera-dl#610] opened 2017-05-29 17:30 UTC
🚨Please review the [Troubleshooting](../#troubleshooting) section before reporting any issue. Don't forget to check also the current issues to avoid duplicates.
Did not find this section in the wiki :-( 

### Subject of the issue
Cannot download - "Connection pool is full"

### Your environment
* Operating System (name/version): Linux hostname 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python version: 2.7.12 & 3.5.2
* coursera-dl version: 0.9.0

### Steps to reproduce
`$ coursera-dl -u me@gmail.com -p "mypassword" neural-networks`
coursera was installed using `sudo -H pip install coursera-dl --upgrade` and `sudo -H pip3 install coursera-dl --upgrade`

### Expected behaviour
Should start downloading

### Actual behaviour
```
coursera_dl version 0.9.0
Downloading class: neural-networks (1 / 1)
Connection pool is full, discarding connection: www.coursera.org
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    load_entry_point('coursera-dl==0.9.0', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python3.5/dist-packages/coursera/coursera_dl.py", line 237, in main
    error_occured, completed = download_class(args, class_name)
  File "/usr/local/lib/python3.5/dist-packages/coursera/coursera_dl.py", line 212, in download_class
    return download_on_demand_class(args, class_name)
  File "/usr/local/lib/python3.5/dist-packages/coursera/coursera_dl.py", line 125, in download_on_demand_class
    extractor = CourseraExtractor(session, args.username, args.password)
  File "/usr/local/lib/python3.5/dist-packages/coursera/extractors.py", line 31, in __init__
    login(session, username, password)
  File "/usr/local/lib/python3.5/dist-packages/coursera/cookies.py", line 145, in login
    headers=headers, allow_redirects=False)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 570, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
```
This did not happen on cygwin/windows10. It worked on cygwin.

**Comment by balta2ar** [comment] 2017-05-29 19:45
duplicate of #609

**Closed by balta2ar** 2017-05-29 19:45 UTC
